type Product = {
    id: number;
    name: string;
    price: number;
    description: string;
    category: string;
    image: string;
}

export const products: Product[] = [
  {
    id: 1,
    name: "Wireless Headphones",
    price: 120,
    description: "High-quality wireless headphones with noise cancellation.",
    category: "Electronics",
    image: "https://via.placeholder.com/300?text=Headphones",
  },
  {
    id: 2,
    name: "Smart Watch",
    price: 180,
    description: "Smart watch with fitness tracking and heart rate monitor.",
    category: "Electronics",
    image: "https://via.placeholder.com/300?text=Smart+Watch",
  },
  {
    id: 3,
    name: "Gaming Mouse",
    price: 45,
    description: "Ergonomic gaming mouse with RGB lighting.",
    category: "Accessories",
    image: "https://via.placeholder.com/300?text=Gaming+Mouse",
  },
  {
    id: 4,
    name: "Mechanical Keyboard",
    price: 95,
    description: "Mechanical keyboard with blue switches.",
    category: "Accessories",
    image: "https://via.placeholder.com/300?text=Keyboard",
  },
  {
    id: 5,
    name: "Laptop Stand",
    price: 35,
    description: "Adjustable aluminum laptop stand.",
    category: "Office",
    image: "https://via.placeholder.com/300?text=Laptop+Stand",
  },
  {
    id: 6,
    name: "USB-C Hub",
    price: 60,
    description: "Multi-port USB-C hub with HDMI and USB 3.0.",
    category: "Electronics",
    image: "https://via.placeholder.com/300?text=USB-C+Hub",
  },
  {
    id: 7,
    name: "Bluetooth Speaker",
    price: 70,
    description: "Portable Bluetooth speaker with deep bass.",
    category: "Audio",
    image: "https://via.placeholder.com/300?text=Speaker",
  },
  {
    id: 8,
    name: "Power Bank",
    price: 40,
    description: "10,000mAh fast charging power bank.",
    category: "Electronics",
    image: "https://via.placeholder.com/300?text=Power+Bank",
  },
  {
    id: 9,
    name: "Desk Lamp",
    price: 30,
    description: "LED desk lamp with adjustable brightness.",
    category: "Office",
    image: "https://via.placeholder.com/300?text=Desk+Lamp",
  },
  {
    id: 10,
    name: "External SSD",
    price: 150,
    description: "1TB external SSD with high-speed transfer.",
    category: "Storage",
    image: "https://via.placeholder.com/300?text=SSD",
  },
  {
    id: 11,
    name: "Webcam",
    price: 85,
    description: "Full HD webcam for streaming and meetings.",
    category: "Electronics",
    image: "https://via.placeholder.com/300?text=Webcam",
  },
  {
    id: 12,
    name: "Noise Cancelling Earbuds",
    price: 110,
    description: "Wireless earbuds with active noise cancellation.",
    category: "Audio",
    image: "https://via.placeholder.com/300?text=Earbuds",
  },
  {
    id: 13,
    name: "Phone Stand",
    price: 15,
    description: "Compact phone stand for desk use.",
    category: "Accessories",
    image: "https://via.placeholder.com/300?text=Phone+Stand",
  },
  {
    id: 14,
    name: "Monitor 27 inch",
    price: 280,
    description: "27-inch Full HD monitor with IPS panel.",
    category: "Electronics",
    image: "https://via.placeholder.com/300?text=Monitor",
  },
  {
    id: 15,
    name: "Wireless Charger",
    price: 25,
    description: "Fast wireless charging pad.",
    category: "Accessories",
    image: "https://via.placeholder.com/300?text=Wireless+Charger",
  },
  {
    id: 16,
    name: "Backpack",
    price: 65,
    description: "Water-resistant laptop backpack.",
    category: "Fashion",
    image: "https://via.placeholder.com/300?text=Backpack",
  },
  {
    id: 17,
    name: "Smartphone Tripod",
    price: 28,
    description: "Flexible tripod for smartphones.",
    category: "Photography",
    image: "https://via.placeholder.com/300?text=Tripod",
  },
  {
    id: 18,
    name: "Graphic Tablet",
    price: 130,
    description: "Drawing tablet for designers and artists.",
    category: "Design",
    image: "https://via.placeholder.com/300?text=Tablet",
  },
  {
    id: 19,
    name: "Office Chair",
    price: 220,
    description: "Ergonomic office chair with lumbar support.",
    category: "Furniture",
    image: "https://via.placeholder.com/300?text=Office+Chair",
  },
  {
    id: 20,
    name: "VR Headset",
    price: 350,
    description: "Virtual reality headset for immersive gaming.",
    category: "Gaming",
    image: "https://via.placeholder.com/300?text=VR+Headset",
  },
];
